### ISSUE TITLE
Implement import method

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/fsal#15]
Client should provide an import method that allows librarian to import content from any location. The method should behave like move() except that the source directory can be _outside_ the directory tree managed by FSAL.

**Comment by foxbunny** [comment]
@integricho Anything missing?

**Comment by goodbadwolf** [comment]
If there are any existing files, should they be overwritten?

**Comment by foxbunny** [comment]
Existing files should be kept.

**Comment by afaikafk** [comment]
Accurate, I think that's what we need

**Comment by goodbadwolf** [comment]
Resolved in 8741ada7ab0534a72e03121f4cbf22caa2fa83c5
