### ISSUE TITLE
Blacklist configuration should support patterns similar to .gitignore patterns

### ISSUE THREAD

**Issue by goodbadwolf** [Outernet-Project/fsal#30]
Preferred enhancements:
- Patterns without leading slash should match at any hierarchy
- glob matching

**Comment by foxbunny** [comment]
Actually, maybe it would be better to just use regexes.

**Comment by goodbadwolf** [comment]
Regex it is.
Resolved in bd03227eac0e80d011309849bfc18dfa1c5e4eec
