### ISSUE TITLE
Subfolder within an ignored folder is shown in file list, allows access to ignored parent

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/fsal#31]
The 'updates' name is in the list of blacklisted paths as seen [here](https://github.com/Outernet-Project/outerbox/blob/master/rootfs/rootfs_overlay/etc/fsal.ini#L16). The path 'updates/wt200' still appears in Librarian's file listing:

![2016-02-07-231120_524x308_scrot](https://cloud.githubusercontent.com/assets/65413/12875711/4d965e90-cdf0-11e5-90ac-3dd1a8dbfcee.png)

Going into the 'wt200' folder causes the URL to become '/en/files/updates/wt200':

![2016-02-07-231202_402x207_scrot](https://cloud.githubusercontent.com/assets/65413/12875719/90b85980-cdf0-11e5-8204-8d5a6f5cf505.png)

From there, it is possible to go up one level and enter the ignored path (though this is probably a Librarian issue, as the listing is empty).

![2016-02-07-231411_417x196_scrot](https://cloud.githubusercontent.com/assets/65413/12875723/a5c94208-cdf0-11e5-8eaf-ce31465175cb.png)

**Comment by goodbadwolf** [comment]
Fixed in 7ef6fd3c5176c1baefef78597bd8b1afff172d38
