### ISSUE TITLE
Directory traversal attack vector

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/fsal#6]
Calling search function with double-dot-slash will cause FSAL to return paths outside the designated library. All paths should be calculated as if the designated library directory is the root of the filesystem.

**Comment by foxbunny** [comment]
Now every query to `listdir()` seems to perform a search. This is possibly due to missing `/` in the requested path.

**Comment by goodbadwolf** [comment]
Fixed in 8361318d89f78867ad8047a82307343fe5c5dbc8
